# Generated by Django 6.1.1 on 2026-09-29 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('school', models.CharField(blank=True, max_length=120)),
                ('grad_year', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=40)),
                ('height_in', models.IntegerField(blank=True, null=True)),
                ('weight_lb', models.IntegerField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('metric', models.CharField(max_length=40)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(max_length=12)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('focus', models.CharField(blank=True, max_length=60)),
                ('duration_min', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill_name', models.CharField(max_length=80)),
                ('target', models.CharField(blank=True, max_length=40)),
                ('completed', models.BooleanField(default=False)),
                ('made', models.IntegerField(blank=True, null=True)),
                ('attempted', models.IntegerField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.workout')),
            ],
        ),
    ]
