# Generated by Django 6.1.1 on 2026-10-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutset',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='workout',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
