# Generated by Django 6.1.1 on 2026-10-02 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_alter_workoutset_options_workout_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='archetype',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='athlete',
            name='wingspan_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('url', models.URLField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
