# Generated by Django 6.1.1 on 2026-10-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_athlete_archetype_athlete_wingspan_in_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='archetype',
        ),
    ]
