# Generated by Django 6.1.1 on 2026-10-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_remove_athlete_archetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='on_leaderboard',
            field=models.BooleanField(default=False),
        ),
    ]
