# Generated by Django 6.1.1 on 2026-10-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_athlete_on_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet', models.CharField(choices=[('espn', 'ESPN'), ('247sports', '247Sports'), ('on3', 'On3'), ('rivals', 'Rivals'), ('maxpreps', 'MaxPreps'), ('usatoday', 'USA Today')], max_length=20)),
                ('stars', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('national_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('position_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('state_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(max_length=300)),
                ('checked_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
            ],
            options={
                'ordering': ['outlet', '-checked_on'],
            },
        ),
    ]
