# Generated by Django 6.1.1 on 2026-10-07 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='coach_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='athlete',
            name='coach_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='athlete',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='athlete',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='athlete',
            name='parent_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='athlete',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='show_coach_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='show_contact_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='athlete',
            name='show_gpa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='show_parent_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='show_rankings_highlights',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='show_school',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='show_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PublishConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('parent', 'Parent or guardian'), ('self', 'Athlete, 18 or older')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('shown', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
