# Generated by Django 6.1.1 on 2026-10-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0007_athlete_coach_email_athlete_coach_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('athlete', 'Athlete'), ('coach', 'Coach')], max_length=10)),
                ('content', models.TextField()),
                ('counted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
