# Generated by Django 6.1.1 on 2026-10-09 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0008_coachmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachmessage',
            name='plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachmessage',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletes.workout'),
        ),
    ]
